# dist: trusty # KVM Setup

notifications:
  email: false

os:
  - linux
  - osx

language: go

go:
    - 1.9

install:
  - go get github.com/whyrusleeping/gx
  - go get github.com/whyrusleeping/gx-go
  - gx install
  - gx-go rw

script:
  - go vet
  - go test -v ./...

notifications:
  email: false
